//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by WINDOM.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define IDD_DIALOG_SCORES               102
#define IDD_NAME                        103
#define IDD_DIALOG_NAME                 104
#define IDD_DIALOG1                     105
#define IDD_SCORES                      105
#define IDC_NAME1                       1000
#define IDC_NAME2                       1001
#define IDC_NAME                        1001
#define IDC_NAME3                       1002
#define IDC_EDIT_NAME                   1002
#define IDC_NAME4                       1003
#define IDC_EDIT_NAME1                  1003
#define IDC_NAME5                       1004
#define IDC_EDIT_NAME2                  1004
#define IDC_NAME6                       1005
#define IDC_EDIT_NAME3                  1005
#define IDC_NAME7                       1006
#define IDC_EDIT_NAME4                  1006
#define IDC_NAME8                       1007
#define IDC_EDIT_NAME5                  1007
#define IDC_NAME9                       1008
#define IDC_EDIT_NAME6                  1008
#define IDC_NAME10                      1009
#define IDC_EDIT_NAME7                  1009
#define IDC_SCORE1                      1010
#define IDC_EDIT_NAME8                  1010
#define IDC_SCORE2                      1011
#define IDC_EDIT_NAME9                  1011
#define IDC_SCORE3                      1012
#define IDC_EDIT_NAME10                 1012
#define IDC_SCORE4                      1013
#define IDC_EDIT_SCORE1                 1013
#define IDC_SCORE5                      1014
#define IDC_EDIT_SCORE2                 1014
#define IDC_SCORE6                      1015
#define IDC_EDIT_SCORE3                 1015
#define IDC_SCORE7                      1016
#define IDC_EDIT_SCORE4                 1016
#define IDC_SCORE8                      1017
#define IDC_EDIT_SCORE5                 1017
#define IDC_SCORE9                      1018
#define IDC_EDIT_SCORE6                 1018
#define IDC_SCORE10                     1019
#define IDC_EDIT_SCORE7                 1019
#define IDC_EDIT_SCORE8                 1020
#define IDC_EDIT_SCORE9                 1021
#define IDC_EDIT_SCORE10                1022
#define ID_FILE_SCORES                  32771
#define ID_FILE_SCORE                   32773
#define ID_OPTIONS_SOUND                32774
#define ID_OPTIONS_PREVIEW              32775
#define ID_HELP_USING2                  57670
#define ID_HELP_INDEX2                  57671

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1027
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
